# Generated by Django 5.1.2 on 2024-12-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='image_check',
        ),
        migrations.RemoveConstraint(
            model_name='exercise',
            name='video_check',
        ),
    ]
