# Generated by Django 5.1.2 on 2024-12-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessor', '0005_account_workouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.JSONField(default=list)),
                ('accountRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessor.account')),
            ],
        ),
    ]
